sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - python: 2.7
      script: tox -e docs
  include:
    - python: 2.7
      script: tox -e lint
install:
  - pip install tox-travis textblob
  - python -m textblob.download_corpora
script: tox
