sudo: false
language: python
python:
  - 2.7
env:
  - TOX_ENV=py27-django17
  - TOX_ENV=py34-django17
  - TOX_ENV=py35-django17
  - TOX_ENV=py36-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py35-django18
  - TOX_ENV=py36-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py35-django19
  - TOX_ENV=py36-django19
  - TOX_ENV=py27-django110
  - TOX_ENV=py34-django110
  - TOX_ENV=py35-django110
  - TOX_ENV=py36-django110
  - TOX_ENV=py27-django111
  - TOX_ENV=py34-django111
  - TOX_ENV=py35-django111
  - TOX_ENV=py36-django111
  - TOX_ENV=docs
  - TOX_ENV=lint
install:
  - pip install tox textblob
  - python -m textblob.download_corpora
script: tox -e $TOX_ENV
